# Generated by Django 3.1.7 on 2021-03-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0002_auto_20210323_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosmicsource',
            old_name='alternative_name',
            new_name='name2',
        ),
        migrations.AddField(
            model_name='cosmicsource',
            name='name3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='b_v_color_index',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='equatorial_dec',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='equatorial_ra',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='galactic_latitude',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='galactic_longitude',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='orbital_period',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='positional_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='pulse_period',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='u_b_color_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='v_magnitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='x_ray_flux',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
    ]
