# Generated by Django 3.1.7 on 2021-03-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0003_auto_20210324_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmicsource',
            name='galactic_latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='galactic_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
