# Generated by Django 3.1.7 on 2021-03-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0004_auto_20210324_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmicsource',
            name='equatorial_dec',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='equatorial_ra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
