# Generated by Django 3.1.7 on 2021-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0005_auto_20210324_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmicsource',
            name='equatorial_dec',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='equatorial_ra',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='galactic_latitude',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='galactic_longitude',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cosmicsource',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
