# Generated by Django 3.1.7 on 2021-03-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0007_auto_20210327_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='paper_url',
        ),
        migrations.AddField(
            model_name='publication',
            name='code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
