# Generated by Django 3.1.7 on 2021-03-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0008_auto_20210327_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='observation_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
