# Generated by Django 3.1.7 on 2021-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0009_publication_observation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='observation_id',
        ),
        migrations.AddField(
            model_name='astrosat',
            name='observation_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
